# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - typedoc.json
      - docs/**

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate docs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci && npm run docs
      - run: |
          git config --global user.name 'Github Automation'
          git config --global user.email 'drew887@users.noreply.github.com'
          git add docs
          (git diff --quiet && git diff --staged --quiet) || (git commit -m "docs: Regenerated Docs Folder" && git push)
